/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/F70ypoFzTcf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"

export function compnav() {
  return (
    <header className="flex h-16 w-full shrink-0 items-center px-4 md:px-6">
      <div className="flex items-center justify-between w-full">
        <Link className="flex items-center" href="#">
          <MountainIcon className="h-6 w-6 mx-auto" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <div className="flex items-center gap-4 lg:hidden">
          <Link
            className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
            href="#"
          >
            Apply Now
          </Link>
          <Sheet>
            <SheetTrigger asChild>
              <Button className="rounded-full" size="icon" variant="outline">
                <MenuIcon className="h-6 w-6" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left">
              <nav className="grid gap-2 py-6">
                <Link className="font-bold" href="#">
                  Use cases
                </Link>
                <Link className="font-bold" href="#">
                  Talents
                </Link>
                <Link className="font-bold" href="#">
                  Events
                </Link>
                <Link className="font-bold" href="#">
                  About Us
                </Link>
                <Link className="font-bold" href="#">
                  Pricing
                </Link>
                <Popover>
                  <PopoverTrigger asChild>
                    <Link className="font-bold flex items-center" href="#">
                      Solution
                      <ChevronDownIcon className="ml-2 h-4 w-4 text-gray-500 dark:text-gray-400" />
                    </Link>
                  </PopoverTrigger>
                  <PopoverContent align="end" className="p-0">
                    <div className="grid grid-cols-2 gap-4 p-4">
                      <div className="space-y-2">
                        <h4 className="text-sm font-medium">For Students</h4>
                        <ul className="space-y-1 text-sm">
                          <li>Mentorship</li>
                          <li>Job Ready</li>
                          <li>Thought Leader</li>
                          <li>Students activity</li>
                        </ul>
                      </div>
                      <div className="space-y-2">
                        <h4 className="text-sm font-medium">For Partners</h4>
                        <ul className="space-y-1 text-sm">
                          <li>Events Sponsor</li>
                          <li>Get Talents</li>
                        </ul>
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </nav>
            </SheetContent>
          </Sheet>
        </div>
        <nav className="hidden flex-1 flex-row items-center justify-center gap-5 text-sm font-medium lg:flex max-w-[1400px] mx-auto">
          <Link className="font-bold" href="#">
            Use cases
          </Link>
          <Link className="font-bold" href="#">
            Talents
          </Link>
          <Link className="font-bold" href="#">
            Events
          </Link>
          <Link className="font-bold" href="#">
            About Us
          </Link>
          <Link className="font-bold" href="#">
            Pricing
          </Link>
          <Popover>
            <PopoverTrigger asChild>
              <Link className="font-bold flex items-center" href="#">
                Solution
                <ChevronDownIcon className="ml-2 h-4 w-4 text-gray-500 dark:text-gray-400" />
              </Link>
            </PopoverTrigger>
            <PopoverContent align="end" className="p-0">
              <div className="grid grid-cols-2 gap-4 p-4">
                <div className="space-y-2">
                  <h4 className="text-sm font-medium">For Students</h4>
                  <ul className="space-y-1 text-sm">
                    <li>Mentorship</li>
                    <li>Job Ready</li>
                    <li>Thought Leader</li>
                    <li>Students activity</li>
                  </ul>
                </div>
                <div className="space-y-2">
                  <h4 className="text-sm font-medium">For Partners</h4>
                  <ul className="space-y-1 text-sm">
                    <li>Events Sponsor</li>
                    <li>Get Talents</li>
                  </ul>
                </div>
              </div>
            </PopoverContent>
          </Popover>
        </nav>
      </div>
    </header>
  )
}

function ChevronDownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MenuIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
